export enum KeyEnum {
  // Teclas de control
  Backspace = "Backspace",
  Tab = "Tab",
  Enter = "Enter",
  Shift = "Shift",
  Control = "Control",
  Alt = "Alt",
  Pause = "Pause",
  CapsLock = "CapsLock",
  Escape = "Escape",
  Space = " ",
  PageUp = "PageUp",
  PageDown = "PageDown",
  End = "End",
  Home = "Home",
  ArrowLeft = "ArrowLeft",
  ArrowUp = "ArrowUp",
  ArrowRight = "ArrowRight",
  ArrowDown = "ArrowDown",
  Insert = "Insert",
  Delete = "Delete",
  Meta = "Meta", // Tecla Windows o Command en Mac
  ContextMenu = "ContextMenu", // Tecla de menú de contexto

  // Teclas de función
  F1 = "F1",
  F2 = "F2",
  F3 = "F3",
  F4 = "F4",
  F5 = "F5",
  F6 = "F6",
  F7 = "F7",
  F8 = "F8",
  F9 = "F9",
  F10 = "F10",
  F11 = "F11",
  F12 = "F12",

  // Bloqueo y otras teclas
  NumLock = "NumLock",
  ScrollLock = "ScrollLock",

  // Caracteres alfanuméricos
  A = "a",
  B = "b",
  C = "c",
  D = "d",
  E = "e",
  F = "f",
  G = "g",
  H = "h",
  I = "i",
  J = "j",
  K = "k",
  L = "l",
  M = "m",
  N = "n",
  O = "o",
  P = "p",
  Q = "q",
  R = "r",
  S = "s",
  T = "t",
  U = "u",
  V = "v",
  W = "w",
  X = "x",
  Y = "y",
  Z = "z",

  // Números del teclado principal
  Digit0 = "0",
  Digit1 = "1",
  Digit2 = "2",
  Digit3 = "3",
  Digit4 = "4",
  Digit5 = "5",
  Digit6 = "6",
  Digit7 = "7",
  Digit8 = "8",
  Digit9 = "9",

  // Números del teclado numérico
  Numpad0 = "0",
  Numpad1 = "1",
  Numpad2 = "2",
  Numpad3 = "3",
  Numpad4 = "4",
  Numpad5 = "5",
  Numpad6 = "6",
  Numpad7 = "7",
  Numpad8 = "8",
  Numpad9 = "9",
  NumpadMultiply = "*",
  NumpadAdd = "+",
  NumpadSubtract = "-",
  NumpadDecimal = ".",
  NumpadDivide = "/",

  // Símbolos y otros caracteres
  SemiColon = ";",
  Equal = "=",
  Comma = ",",
  Dash = "-",
  Period = ".",
  ForwardSlash = "/",
  BackSlash = "\\",
  GraveAccent = "`",
  OpenBracket = "[",
  CloseBracket = "]",
  Quote = "'",

  // Modificadores y teclas de comandos
  AltGraph = "AltGraph",
  Context = "Context",
  Function = "Fn",
  FnLock = "FnLock",
  PrintScreen = "PrintScreen",
  Scroll = "Scroll",
  PauseBreak = "PauseBreak",
  Select = "Select",
  VolumeMute = "VolumeMute",
  VolumeDown = "VolumeDown",
  VolumeUp = "VolumeUp",
  MediaTrackNext = "MediaTrackNext",
  MediaTrackPrevious = "MediaTrackPrevious",
  MediaPlayPause = "MediaPlayPause",
  MediaStop = "MediaStop",
  BrowserBack = "BrowserBack",
  BrowserForward = "BrowserForward",
  BrowserRefresh = "BrowserRefresh",
  BrowserStop = "BrowserStop",
  BrowserSearch = "BrowserSearch",
  BrowserFavorites = "BrowserFavorites",
  BrowserHome = "BrowserHome",
  LaunchMail = "LaunchMail",
  LaunchMediaSelect = "LaunchMediaSelect",
  LaunchApp1 = "LaunchApp1",
  LaunchApp2 = "LaunchApp2"
}

export default KeyEnum;
